### PR TITLE
Foundation of Viewable Itinerary

### PR DESCRIPTION
**Pull request by GrantMatejka**

### CODE REVIEW

**Comment by GrantMatejka** [comment]
@exzhou Thanks for your input, yeah the new post card component needs a navigation prop to work properly so it will take some time to transition over to the new system. I think I have it working in by build as of now so will incorporate the fix in the next pull

**Comment by GrantMatejka** [comment]
@abhishurawka22 Thanks for the input, and yeah that bug was just my bad as I didn't take full integration seriously yet but I fixed it and will be fixed in the next PR.

**Comment by ShreyaTumma** [comment]
@GrantMatejka I'm running into the same error that was addressed above, but other than that the itinerary looks great and I am excited to see how it develops further!
When I run the app from the web, the components of the last PostCard are shifted and I am wondering if this is occurring on your end as well.

**Comment by GrantMatejka** [comment]
Thanks @ShreyaTumma , I had the shifting problem earlier but though I figured it out, but guess its not gone just yet so I'll look into it again. I know it's because of Location text pushing off other stuff so want to see if text scaling would be possible

**Comment by shauryamago12** [comment]
Besides the above mentioned issues, looks good to me! Nice work

**Comment by GrantMatejka** [comment]
@shauryamago12 thanks!

**Pull request merged**
