### PR TITLE
Exzhou

### PR DESCRIPTION
**Pull request by exzhou**
Has the create post preview as well as profile pic grab from storage and photo upload and retrieval from fire storage.

### CODE REVIEW

**Comment by ShreyaTumma** [comment]
Hey Eric! The post preview screen looks great and really improves the user's experience when creating a post. Overall, all of the changes look good now that the styling has been fixed.

**Comment by GrantMatejka** [comment]
Good work on getting the photo preview working. It'd be pretty cool if next sprint we can try and get a crop option too. Excited to get this into develop and start working on incorporating dynamic data more

**Comment by exzhou** [comment]
@ShreyaTumma I appreciate the positive feedback, I'm glad to hear that it is working on your end as well! I am also excited to see it added to dev and further improved in later sprints.

**Comment by exzhou** [comment]
@GrantMatejka I hadn't thought about cropping beforehand as an option for photos. I can definitely look into this idea for next sprint. I was wondering what kind of situations we might need to crop the photo for. I'm excited to see how this will affect our app.

**Comment by shauryamago12** [comment]
Good job on the photo preview, everything works on my end and looks clean with the styling changes!

**Comment by exzhou** [comment]
Thanks for your support @abhishurawka22 and @shauryamago12, I'm encouraged to keep working on this and improving its designs to better fit our travel itinerary needs for future. The style is all thanks to @GrantMatejka the style/git master.

**Pull request merged**
