### PR TITLE
Shreya - Autocomplete

### PR DESCRIPTION
**Pull request by ShreyaTumma**
Autocomplete formatted, and now user can search by country.

### CODE REVIEW

**Comment by abhishurawka22** [comment]
This is a huge boost for Baku! Good job fixing the style of the search bar. Autocomplete looks exactly as what we discussed we want to make it. Do you know if it is going to make Baku slow or way bigger in size if we hard code the big list of cities as well?

**Comment by ShreyaTumma** [comment]
@exzhou Thank you for helping me with the merge conflicts in package-lock.json! I am also glad to hear that the keyboard is not obstructing the drop down box on ios devices. For the next sprint I will look into fixing this keyboard issue with android devices.

**Comment by ShreyaTumma** [comment]
@GrantMatejka that is an excellent question! For testing purposes I have stored the JSON data locally, but in the future it will probably be best to store it through FS. This way if any changes (the addition of newly discovered cities or countries) need to be made to the file, it will automatically update for each device. As for the 'absolute' positioning, I will continue to replace those styles in my new commits. Thank you for your feedback!

**Comment by ShreyaTumma** [comment]
@djuliano14 thank you for your feedback! I agree that it would be useful to have the autocomplete component in a separate file so that it can be referenced in other classes of Baku. I hope to implement this early in the next sprint. I am not sure that we will be able to find a free third party location service, but I will continue to look into this.

**Comment by ShreyaTumma** [comment]
@abhishurawka22 I am glad to see your positive response on this progress, thank you! I am not sure how much slower Baku will become with a larger file, but I will research about this more before our next meeting. As mentioned above, I think that storing this data on FS will be more beneficial for our app and will hopefully handle any potential lagging issues we may have.

**Comment by shauryamago12** [comment]
Looks good to me, nice job

**Pull request merged**
