### PR TITLE
Exzhou

### PR DESCRIPTION
**Pull request by exzhou**

### CODE REVIEW

**Comment by GrantMatejka** [comment]
Would there be anyway to consolidate the 'then' clauses? Maybe move functionality to a dedicated method? Also renaming of state variables to be more cohesive and understandable. Like what's 'photox'?

All in all good work and thanks for putting in the scrollviews.
We can address these concerns at a later time as they're style based.

**Comment by exzhou** [comment]
@GrantMatejka I appreciate the feedback, I was planning on implementing a fire class to hold the firestore related functionality and pass those to the classes that need firestore to limit the functions in each class, this will also reduce the then clauses as the firebase functions can be called within the handle functions.

**Comment by abhishurawka22** [comment]
Good job on the Facebook and Google icons on the signup page! I tried making all the buttons more compact but this one looks better and also saves time as the user does not need to scroll down anymore

**Comment by exzhou** [comment]
@abhishurawka22 I appreciate the positive response! I felt like it would be a cleaner design for our login page which I feel it accomplishes.

**Pull request merged**
