### PR TITLE
Shaurya

### PR DESCRIPTION
**Pull request by shauryamago12**
- enabled bio in profileTab
- added show password option when logging in
- auto format phone number when typing phone number in edit and create profile
- "mock" unit tests

### CODE REVIEW

**Comment by GrantMatejka** [comment]
Sweet, thanks for putting some tests together for us. Looks good and I could really see some users wanting to be able to see their password.

**Comment by abhishurawka22** [comment]
Good work! Auto-format is something users would want to be using and is good to have that in Baku. The tests seem to be providing more coverage as well!

**Comment by ShreyaTumma** [comment]
Nice touch with the auto formatting of the phone number. All of these details make the app feel more professional and add to the user experience!

**Comment by shauryamago12** [comment]
Thank you all for the feedback! @ShreyaTumma @GrantMatejka @abhishurawka22 @exzhou @djuliano14

**Pull request merged**
