### PR TITLE
Abhishu

### PR DESCRIPTION
**Pull request by abhishurawka22**
A lot of backend Firestore stuff.

### CODE REVIEW

**Comment by GrantMatejka** [comment]
Good work setting up more stuff to firestore. Hopefully we can adapt this logic to all areas of the app. Good job

**Comment by shauryamago12** [comment]
Looking good, adding more Firestore changes is perfect. As Shreya said though, when tapping Submit on the Create profile screen, you get a few errors if you're on Android. You can fix this by commenting out line 62 in signupScreen.js and changing lines 129 and 142 in createProfileScreen.js to "borderRadius: 86".

Nice work!

**Comment by djuliano14** [comment]
Lookin' good Abhi. This Cypress organization will be super helpful moving forward. Create profile looks awesome and its working as expected for me too.

**Comment by abhishurawka22** [comment]
@GrantMatejka @exzhou @ShreyaTumma @djuliano14 @shauryamago12 Thank you for the positive feedback!! Glad we could work as a team and fix the border-radius issue on android :)

**Pull request merged**
