### PR TITLE
dropdown component and assets edited

### PR DESCRIPTION
**Pull request by djuliano14**
resubmit because accidentally tried to base with master on last pull req

### CODE REVIEW

**Comment by GrantMatejka** [comment]
Looks good, we should try and stay away from such custom styling but thanks for putting this together.

**Comment by shauryamago12** [comment]
Looks good, nice work!

**Comment by djuliano14** [comment]
> Looks good, we should try and stay away from such custom styling but thanks for putting this together.

Good point. This was a dependency so I didn't think about that. Good future note.

**Comment by exzhou** [comment]
The dropdowns look cool, but I don't know if they work for passing the information.

**Comment by abhishurawka22** [comment]
It looks good! I always wanted to have a dropdown feature glad we made it happen!

**Comment by ShreyaTumma** [comment]
I am glad you were able to find a work around for our create post tab! Good job implementing the drop down feature. I think this will help us standardize our collections in FS.

**Pull request merged**
